import "./globals.css";
import type { Metadata } from "next";
import { poppins } from "@/components/ui/font/f";
import DesktopNav from "@/components/appComp/navbar/desktopNav";
import { MobileNav } from "@/components/appComp/navbar/mobileNav";
import { QuizProvider } from "@/context/contextProvider";
import { Toaster } from 'react-hot-toast'
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create Quiz app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Toaster
          position="top-right"
          reverseOrder={false}
        />

        <QuizProvider>
          <div className="flex md:flex-row flex-col min-h-screen h-screen max-w-7xl mx-auto">
            <MobileNav />
            <DesktopNav />
            <div className="w-full h-full md:border-input md:border-l-2 md:py-8 py-3 md:px-4 px-2 overflow-y-auto scroll-smooth">
              {children}
            </div>
          </div>
        </QuizProvider>
      </body>
    </html>
  );
}
