import "./globals.css";
import type { Metadata } from "next";
import { poppins } from "@/components/ui/font/f";
import DesktopNav from "@/components/appComp/navbar/desktopNav";
import { MobileNav } from "@/components/appComp/navbar/mobileNav";
import { QuizProvider } from "@/context/contextProvider";
import { Toaster } from 'react-hot-toast'
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create Quiz app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Toaster
          position="top-right"
          reverseOrder={false}
        />
        
        <QuizProvider>
          <div className="min-h-screen h-screen max-w-7xl mx-auto flex">
            <MobileNav />
            <DesktopNav />
            <div className="md:border-input border-l-2 w-full h-full py-8 px-4 overflow-y-scroll">
              {children}
            </div>
          </div>
        </QuizProvider>
      </body>
    </html>
  );
}
